// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEZpTGYPsH0KAktCtcS6IBnt8iy2FUDEI',
    appId: '1:95777783484:web:77dc9f7d4194b6b77edab9',
    messagingSenderId: '95777783484',
    projectId: 'housecrush-1428e',
    authDomain: 'housecrush-1428e.firebaseapp.com',
    storageBucket: 'housecrush-1428e.appspot.com',
    measurementId: 'G-29RREHPWLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-0iHcJ6e6C_FtDWKkUttX0K3kQMJyR0',
    appId: '1:95777783484:android:225989dd22f914407edab9',
    messagingSenderId: '95777783484',
    projectId: 'housecrush-1428e',
    storageBucket: 'housecrush-1428e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDub2qt9b5GlQz7c1QBLpcH0iXu1U3lswA',
    appId: '1:95777783484:ios:8f2cfa1cb5905c627edab9',
    messagingSenderId: '95777783484',
    projectId: 'housecrush-1428e',
    storageBucket: 'housecrush-1428e.appspot.com',
    iosClientId: '95777783484-7uu62pq34rifqj1ckrh81bavcbnr88i0.apps.googleusercontent.com',
    iosBundleId: 'de.schultek.housecrush',
  );
}
