name: housecrush_app
description: Design your dream house. Find out what it costs. Cry a lot.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  android_id: ^0.1.3+1
  another_stepper: ^1.1.6
  beamer: ^1.5.3
  cloud_firestore: ^4.1.0
  chips_choice: ^3.0.0
  collection: ^1.16.0
  crypto: ^3.0.2
  dart_mappable: ^1.2.0
  device_info_plus: ^8.0.0
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  logger: ^1.1.0
  riverpod_context: ^0.3.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_mappable_builder: ^1.2.1
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  fonts:
  - family: Axel
    fonts:
      - asset: lib/assets/fonts/axel_regular.ttf
      - asset: lib/assets/fonts/axel_bold.ttf
        weight: 700
