name: Deploy to Firebase Hosting
on:
  workflow_dispatch
  push:
    branches:
      - main
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: |
          cd app
          flutter pub get
          flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOUSECRUSH_1428E }}'
          projectId: housecrush-1428e
          channelId: live
